# Generated by Django 4.1.1 on 2022-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=1, max_length=50, verbose_name='Género'),
            preserve_default=False,
        ),
    ]
