# Generated by Django 4.1.1 on 2022-09-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_category_alter_employee_avatar_alter_employee_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ManyToManyField(to='erp.category', verbose_name='Categoría'),
        ),
    ]
