# Generated by Django 4.1.1 on 2022-09-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_employee_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='type',
            table='tipo',
        ),
    ]
