# Generated by Django 4.1.1 on 2022-09-20 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de venta'),
        ),
    ]
