# Generated by Django 4.1.1 on 2022-09-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_category_date_creation_category_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
