# Generated by Django 4.1.1 on 2022-09-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_rename_created_at_sale_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_updated',
        ),
    ]
