# Generated by Django 4.1.1 on 2022-09-26 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_alter_sale_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de venta'),
        ),
    ]
