# Generated by Django 4.1.1 on 2022-10-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_alter_sale_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailSale',
            new_name='SaleProduct',
        ),
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'default_permissions': (), 'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalle de Ventas'},
        ),
        migrations.AddField(
            model_name='sale',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total IVA'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Categoría'),
        ),
    ]
