# Generated by Django 4.1.1 on 2022-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_alter_client_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=0, max_length=100, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(default=0, max_length=12, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
