# Generated by Django 4.1.1 on 2022-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_client_email_client_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos'),
        ),
    ]
